:PROPERTIES:
:ID:       B8B2689E-5F27-4C11-9727-243BC06F5970
:END:
#+title: 一瞬间的思考
#+author: RDS
#+filetags: :main:

* 2025 (15)

** <2025-12-09 Tue 09:48>
事情分为简单和复杂的两种，区分的标准并不是难不难，而是是否是线性的、少维度的。如
果一件事涉及多个因素，而因素之间还是彼此耦合的，就可以视为复杂。反之就是简单的。

** <2025-12-03 Wed 20:52>
如果不是发自内心的喜欢做一件事，就不要勉强了，迟早会出事的。不要为了其他任何的
“利益”，放弃内心的追求。

** <2025-08-25 Mon 10:33>
考虑一个问题，一定要从多个角度，事情的双方不同视角来看待。不能自己想当然地以为会
是怎样，就觉得一定会是这样。即使自己是对的，也不代表这是现实。

** <2025-07-23 Wed 15:31>
不能手里有什么工具，就去解决什么问题。而是面对问题，分析需要用什么工具才能解决，
然后才去寻找工具或者发明工具。这个次序不能颠倒了，否则，一定是拿着榔头满世界找钉
子。

我在去年的 10 月份就理解了这个思维，但是没有很好地付诸实践。因此，理论是一回事，
实际是另一回事。“知行合一”，不是那么简单的。

** <2025-07-17 Thu 10:43>
如果一个软件，能够完成自己的功能，就不要轻易替换。其他新出现的替代品，可以尝试，
但不要随意作为生产力工具。要记住：最大的成本是时间成本。

** <2025-07-12 Sat 16:57>
控制住自己，不要听到任何相左的声音，就马上产生“”敌对”反应，然后情绪失控。好的应
对方法，是不要有任何应激反应，先找到对方的合理之处，即使非常少。控制，是第一位的。

** <2025-05-15 Thu 15:43>
解决一个问题有很多层次，高层次的采用最好的方法，低层次的采用比较“笨”的方法。如果
问题可以得到解决，越高层次的越好。但能解决问题，才是最重要的。因此，不要低估“笨”
的方法。但是，不能满足于只用“笨”的方法。

** <2025-04-10 Thu 16:05>
试着不去反驳任何观点和结论，只是平和地诉说自己的想法和认识。一定要记住，我自己的
观点也只是暂时的认识而已，不可能保证正确，那又何必强求他人接受我的观点呢？

** <2025-04-02 Wed 09:22>
坦坦荡荡面对现实。不论好与坏的结果，要坦然接受，不惊不燥，更不要不好意思，故意躲
避。实际上，大多数的“不好意思”都是自己以为的。能做到就事论事，不纠结，就好。

** <2025-03-23 Sun 15:06>
听别人说话时，第一反应不要是反驳，要尽可能地听对方合理的一面。即使真的以为对方一
无是处，也用不着证明自己更高明。

** <2025-03-22 Sat 19:08>
说话不要受对面人的影响，不能因为对方快了慢了，自己就跟着加快。要保持自己的节奏，
掌控时间、掌控谈话的方式。最重要的，要表达清楚自己的意见，听明白对方的观点。否则，
谈话就没有意义了。

** <2025-03-20 Thu 15:42>
变化是常态的，一定不要以为什么事情就是铁板钉钉。因此，对各种可能情况，要有心理准
备。但是，也不要事先考虑过多，没必要的焦虑会导致过分紧张。有预期即可。

** <2025-02-11 Tue 13:39>
我无法控制他人如何转变，因为我连自己变向何方都无法掌控。我唯一能做的，就是坚持做
自己，把自己做好。

** <2025-02-11 Tue 11:37>
做好充分的准备，不要期望能哄弄过去。很多机会，其实只有一次，失去了就再也不会重来。

** <2025-01-21 Tue 08:47>
一定要克制住自己的脾气，无论外面是什么样的反对、蔑视甚至侮辱，都不应该转化成愤怒。
不理会就好了。

** <2025-01-18 Sat 10:48>
永远不要自我表扬，即使是真的，也不能从自己的嘴里说出。可以说事实，但不要自己做结
论。

* 2024 (22)
** <2024-12-01 Sun 10:40>
害怕失去，是一种胆怯，必然要把自己依附于某个人某件事。只有自己的内心有坚定的信念，
才可以让自己真正勇敢，才能不害怕。

** <2024-11-28 Thu 10:28>
一旦想明白了一件事情，就不要纠结了。人最宝贵的是时间。

** <2024-11-08 Fri 08:40>
表达尽量不要咄咄逼人，无论对自己的证据和结论多么有信心，因为这样会让听众情绪上受
不了，而我们对话和辩论的主要目的是说服对方，并不是展示自己的优越性。

** <2024-10-13 Sun 17:09>
一定要有问题解决思维。不能手里有什么工具，就一定要用这个工具来解决问题。而应该是
综合判断面临的问题，需要用什么工具合适，就打造这个工具。

** <2024-06-29 Sat 20:06>
如果自己秉承的价值观有明确的判断，那何必需要外界的认可呢？如果需要周围的人赞同与
否来维系自己的观点，说明自己并没有真正的相信。

** <2024-06-03 Mon 15:04>
每一种状态都有自身的价值标准，不要期望把不同状态的优点集中起来，而不想要缺点。更
不要反复去看已经“不在乎”的好处。

<2024-06-18 Tue 15:08>
- 人做决策的时候常常是根据直觉，也就是瞬间就得出了判断，后面的工作只是在为这个决
  策寻找理由。
- 我们学习和读书的目的，就是让这个直觉更可靠一些。
  
** <2024-05-23 Thu 10:52>
永远不要吹嘘自己有什么能力。所有的能力，都是为了完成某一个事业的基础。永远不要觉
得自己有某种能力，是用来吹嘘的资本。

** <2024-05-20 Mon 15:33>
不要吹嘘自己，但也不要轻易贬低自己。过分的谦虚，反而让人觉得虚伪。不卑不亢，真实
坦率，才是最好的方式。

** <2024-05-16 Thu 23:00>
一定要控制住说话。知道什么时候该说，什么时候闭嘴，是极大的智慧。

** <2024-05-10 Fri 20:10>
不要带着情绪说话做事，如果一件事，觉得被冒犯，主要还是因为自己的层次不够，让对方
认为你只值这个待遇。所以，就事论事，同意就合作，不同意就干脆拒绝，然后继续认真做
自己的事。等自己达到了某一高度，自然会有匹配的合作。

** <2024-04-29 Mon 16:09>
自信是一种发自内心的感觉，是真正地相信自己，能够做成事情。凡是需要和别人比较来宽
慰自己的，都是口头的“自信”，其实是内心的虚弱而已。

** <2024-04-29 Mon 13:56>
一旦决定走什么路之后，就不要彷徨，更不要后悔。这山看着那山高，什么都想要，是不可
能的。

自己的路，只是自己的。至于别人是否赞同，一点也不重要。妄图说服别人，也是痴心妄想，
更是毫无必要。

** <2024-04-15 Mon 13:46>
他人的好与坏，不该我来评价，除非影响了我的工作。认真专注自己的事情，才是能做成事
的基础。

** <2024-04-13 Sat 20:38>
急于说服他人，是不自信的表现。如果对自己的认识抱有信心，其实完全不会在乎别人是否
同意。若不同意，是他们的损失。

** <2024-04-11 Thu 17:13>
每个人活在这个世上，都是自己独特的存在和思考。他人的感觉，永远不能代替自己的感受。
因此，好与不好，值不值得，都不必强求他人理解和接受。如果还在通过劝说他人与自己相
同，只能说明自己内心的软弱：因为你自己并没有真正接受自己。

** <2024-04-06 Sat 19:12>
不要抱怨身边没有优秀的人，其实是自己的层次决定了哪些人会出现在自己身边。自己不够
优秀，当然就不会有优秀的人和你结交。

** <2024-03-28 Thu 10:54>
“人无远虑，必有近忧”这句话，现在已经不太适用了。因为现代社会，变化太快，而人的忧
虑，大多来于自我设想的“麻烦”。因此，如果一件事没有发生，就不要轻易假设它会发生，
从而无端自我烦恼；如果一件事发生了，就积极面对，找到应对的办法。

** <2024-01-30 Tue 15:22>
#+begin_quote
越是占有稀缺的资源，就越容易在炫耀性上获得满足。人在比较弱小的时候，最常有的心态
就是“别人有的我不能没有”，言下之意是“我不能被别人落下”，而在变强之后，最常有的心
态就是“别人都有的我不要”，言下之意是“我必须保持优越感，不能让自己降低到那些人的
层次”。在我看来，人的这种心理特质是全部经济学最基础的一条公理。

--- 熊逸
#+end_quote

** <2024-01-25 Thu 10:47>
经济发展需要解决两个本质问题：一是如何把蛋糕做大；二是如何合理分配。假日旅游，其
实只是一个财产重新分配问题，既旅游的人把钱转给饭店、景点、交通等的提供者。但是假
日的消费是虚高的，“高”出理性的部分并没有太多的实际意义。因为财富合理分配，最重要
的是把财富从富人那里合理流向“穷人”，而假日的旅游，富人是不会贡献的。

** <2024-01-18 Thu 11:04>
发现真需求，解决真问题。而不是创造一个“伪”需求，发明一个“伪”技术，去迎合市场。

只有真正解决人们的实际问题的技术和产品，才有生命力。

** <2024-01-06 Sat 09:41>
轻易不要 *judge* 他人，即使在最熟悉的人面前。

** <2024-01-02 Tue 14:56>
能够重复别人的工作是一种能力，但这种能力不足以吸引他人：为什么人家不直接用做得更
好的人的工作呢？除非他们不能容易地得到这种能力。因此，能够做出他人不能简单模仿的
工作，才真正有竞争力。

* 2023 (21)
** <2023-12-24 Sun 20:42>
表达一个观点，一定要拿出证据。如果不能 *prove it*，就不要轻易说出来。

** <2023-12-24 Sun 09:54>
现在，一定要做自己擅长的事。如果自己内心不喜欢的事，即使再勉强，也做不好。比如做
商业，有两种方式，一是拉关系、跑资源、勾兑；二是努力做核心技术。两种都有成功，也
有失败的。但我的性格，实在是不喜欢第一种方式。我做企业，也不完全是为了挣钱。那么，
努力把自己的强项发挥出来，做好核心技术，做到双赢。

** <2023-12-13 Wed 21:32>
做事情尽量做减法，减到无法再减为止。然后全力以赴，把这个问题解决好。

公司的产品必须是自己愿意用的，能实际起作用的。否则，纯粹靠市场营销，即使早期能成
功，迟早会失败的。

** <2023-12-10 Sun 09:28>
一个道理，如果自己没有实践成功，就尽量避免去和他人说教。纸上得来的知识，本事就具
有一定的欺骗性。更何况，好为人师，实在是一个让人讨厌的行为。

** <2023-11-20 Mon 15:56>
现在做事，不能浮夸，投资人真金白银投资的东西，一定是自己可以做出来的。如果自己没
有想清楚，就无法给别人讲清楚，自然就不会真正做出来。

** <2023-11-03 Fri 10:54>
必须要控制自己不停看东西、听东西的欲望，当你被外界的声音全部包围时，实际上自己的
思考是不足的。而真正的领会，必须要通过自己大脑的思考才能内化。

** <2023-10-26 Thu 13:37>
任何时候控制住自己的情绪都是十分重要的，不管面对的人有多熟悉，如何的会迁就自己。
保持谦虚、谨慎，永远都没有坏处。

** <2023-10-19 Thu 10:11>
无论曾经多么好的朋友、爱人，都不会真正了解你自己。其实，自己也不能完全明白自己的
内心的。面对自己的时候，不能伪装，一定要诚实而坦然。否则，欺骗自己，又有什么意义
呢？

** <2023-06-03 Sat 19:22>
能用，就千万不要升级；能工作，就不要随便优化。

“过早优化是万恶之源”，无端升级，尤其是系统级的升级，也是麻烦的根源。时间，一定要
用于解决有意义的问题。

** <2023-04-20 Thu 15:25>
谈话能做到戛然而止、当机立断，就是高境界了。否则，兴高采烈地一直说下去，不知道节
制，反而暴露了弱点。

** <2023-04-11 Tue 08:34>
如果我老是盯着西华大学的人和事，就说明我不自觉地认为自己就是西华大学这样的水平的
人。正如那句话：和你对抗的人的水平，决定了你的水准。

** <2023-03-21 Tue 09:23>
读书不要读合集，一本一本地认真看。好处是可以对具体的每一本做出评价。

** <2023-03-14 Tue 17:19>
一件事情，当你感觉不对劲的时候，就是不对劲了。要么就采取措施解决它，要么就及时终
止它。否则，任其自然地发展下去，一定会非常不对劲。

** <2023-03-14 Tue 15:14>
事情是否做成，才是判定水平的标准。只是表现自己读了多少书，掌握了多少知识，都是虚
的。

** <2023-03-05 Sun 11:30>
表扬自己的话，一定要从第三方的口里传出，无论如何不能自我标榜。

** <2023-03-04 Sat 20:24>
要向他人表明一个观点，最好的方式就是自己亲自证明它是对的：要么科学推理；要么自己
把它做出来。

** <2023-03-02 Thu 14:54>
一个新技术/新工具的发明和应用，最主要的是要解决其他技术没法完成的功能，而不能仅
仅停留在：我用了一个新玩意，但只能重复别人已经完成的工作。

** <2023-02-19 Sun 10:38>
如果一个政策制定者，本身有好的初衷，但是结果并不美好；而私心较重，本意是为自己谋
利但最后结果是皆大欢喜。后一种，如果事先知道结果，当然大家都会赞成。可是，这种可
能性是非常小的。更可能的情况是，施政者，私心满满，结果是除了他自己，其余人都受害。
那么，在实际的复杂情况中，如何真正判断一个政策的好恶？

** <2023-01-12 Thu 14:28>
兜兜转转，又用回 org-mode 方式来记笔记。确实，那些花里胡哨的软件：*Obsidian*,
*Evernote*, ..., 等等，都无法真正做到文本格式存储。这不利于后期处理。所以，对于
程序员思维的我来说，还是用 org-mode 吧。

** Jan. 06, 2023
大多数人言之无味，主要是两个原因：
1. 没有清晰的观点；
2. 不能清楚表达。

而表达模糊的一个重要原因是写作太差。诚然，现代社会更注重快餐文化。因此，言说比写
作更流行。但是，口头的表达永远都比不上深思熟虑的写作。

我以前满足于可以即兴演讲。但后果是，我所讲的东西，并不能真正保留和传播开来。因为
缺乏严谨的逻辑和思考，一时的口头逞能虽然会带来即时的满足和虚荣，但基本没有太大的
用处。

** Jan. 02, 2023
明确的判断，配以严密的逻辑推理和事实依据，才是有用的。现在，我的判断结论都越来越
少，且越来越模糊，说明思考得越来越贫乏。快节奏的短视频、推特、公众号文章，都不能
增强我思考的力量。相反，它们都在拖我的后腿。因此，必须将注意力转移到更深刻的思考
中来。

* 2022 (22)
** Nov. 14, 2022
“知其不可为而为之”与“随机应变”有什么区别呢？我曾经无数次考虑过这个问题，今天，我
终于想明白了：
- 内心真正的信念是什么；
- 是否有其他更优的方向让你实现理想。

首先，必须明确自己内心的信念和准则。然后，遇到阻力，则仔细寻找是否有更好的办法实
现自己的理想：如果有，则及时止损，快速调整到更好的赛道；如果没有，则只能“知其不
可为而为之”。无论如何，自己最终想得到的是什么，是必须要想清楚的。

** Nov. 10, 2022
知识分两种：一是结论，也就是知识点；二是得出结论的过程和原因。因此，如果一本书偏
重于第一种，则翻翻即可，快速浏览而过；如果偏重第二种，则需细细研读，努力掌握逻辑
过程。

** Nov. 06, 2022
费曼说，如果一个东西我不能独立设计出来，就是没有真正理解它。这句话对我来说，极其
贴切。看很多书，都是概念的堆砌。一个符号到另一个符号，一个定理到另一个定理。为什
么要这么做？如何才能做出来？要解决的问题是什么？必须时刻牢记这些问题。

** Nov. 03, 2022
你所认知和试图寻找的共同体，其实只是一个很小的圈子而已。无论你得到了认同或是抱怨
得不到理解，跳出来看，都只是一个小小的团体。一定要跳出来，站高点看。

** Oct. 18, 2022
判断一件事情的是非，必须有明确而坚定的理由。一旦认定了，就不要轻易更改，尤其不能
简单地以所谓的“成败”论是非。不对的做法和观点，就是不对的。如果连这样的自信都没有，
就白读那么多书、想那么多道理了。

成败有很多因素，可以作为重要的评价指标之一。但是，它绝对不是唯一的指标，甚至在一
些时候，成败都不是最重要的指标。

** Oct. 08, 2022
任何时候，不论面对的是哪种层次的人，都不要表现得自己高人一等。自己明白一些东西，
且不说是否一定是正确的，即使是，也只是表明自己早了一点时间知道而已。所以，谦虚是
发自内心的，而不是装出来的样子。

** Oct. 03, 2022
有一个 idea 总是好的，比什么都没有要强很多。但是，如果只有 idea，却没有如何实现
它的方法、技术、步骤，则这个 idea 大概也只是聊胜于无了。

** Sep. 28, 2022
大多数的争论其实都没有必要，因为双方只是表明自己的观点，而并不需要说服对方。纯靠
逻辑就能证明一方是错误的事情，太少了。

** Sep. 15, 2022
如果一个人还需要得到外界的认可，才认可自己，那他就根本没有真正认可自己。

** Sep. 12, 2022
仅有想法是不够的，如果不能拿出成果，自然不会有人相信你。有时候，成功确实是唯一能
被大家认可的标准。

** Sep. 07, 2022
数学是有实用价值的，但数学真正的意义是建立严密的逻辑体系。这才是真正的“道”，而不
仅仅普通人抱怨的、日常生活是否需要微积分这样荒谬的言论。如果两件事之间，有逻辑关
系没有理清楚，大概率是可能出问题的。而根据墨菲法则，一定会出问题。

** Aug. 10, 2022
任何时候，谦虚谨慎都是必要的。如果你觉得自己取得了一些成绩，固然值得高兴。但一定
要提醒自己，那是因为问题还不够难，还没有遇到真正的挑战。

成功也都是阶段性的，没有永远的成功和失败。

** Jul. 19, 2022
敲键盘实际上是比书写快得多的，到手机输入经常会出错，中文拼音也有很多候选词，严重
影响了思维和速度但无论如何，尽量用键盘。因为后续编辑和再利用的价值是无可比拟的。

在做一件正式的事之前，无论该事情有多小——例如在网上搜索一个问题的答案，如果开始时
可以写下来目的，即使只有一句话，也可以对实施这件事的过程带来极大的便利。

** Jun. 02, 2022
不要轻易否定对方的观点，即使你认为一无是处，也请冷静 10 秒钟，不可脱口而出批判。
无论如何，表现出审慎的同意。

** May 25, 2022
任何情绪状态下都至少保留一丝冷静。低落时也许还好一点，得意或者兴高采烈时，尤其要
注意不可忘形。否则，一定会出现错误，不是说错话，就是做错事。

** May 22, 2022
对于他人的发言，第一反应永远都不要是反驳，即使你觉得对方讲的完全是胡说八道。听完，
首先表示有限赞同，然后语气平和地说出自己的意见。除非你想激怒对方，那就完全反过来
吧。

聆听永远比述说重要！除非是发表演讲，否则一定要做到：自己说的比对方说的要少。而且
在任何时候都不要抢对方的话语，克服抢话毛病的一个方法是，对方说完后，停一秒钟，自
己再开口。

** May 19, 2022
试图给一般的人讲述自己的理想，只能是一种妄念。实际上他们不能真正理解你，也不想理
解你。

** Apr. 06, 2022
很多人喜欢高高在上，谈论战略规划、整合资源。但实际上，这其中大多数人都是眼高手低，
根本不能做成实际的事。他们以为自己做的事才是高大上的，但就像公鸡打鸣伴随着太阳初
升，时间久了，公鸡就以为自己不打鸣太阳就不会生起一样，这只是幻觉而已。

这样的人，最适合的场所是一切都已经理顺的体制内。真正有本事的人建好了规矩，他们只
是按部就班。

我不愿意做这样的人。

** Mar. 31, 2022
上次志刚来，感慨的是，有时候我们这样做事值不值。那些麻木而又自私的人，值不值得我
们的付出。现在，我明白了。这些都不是我们应该考虑的重点。我们应该树立明确而坚定的
目标，有自己的理想和信念，坚定地执行下去。而那些所谓的值不值得、以及他人如何看待，
都不应该成为我们完成理想的羁绊。

外人的看得起或者看不起，一点也不重要。其实，没有人真正看你。阻碍自己前进的最大因
素，就是自己的患得患失。

鲁迅先生的内心和外表如此一致，是因为知识分子的风骨，由内而外。

** Mar. 27, 2022
大多数的心理障碍，都来自于内心的脆弱，主要是担心自己在外人的形象受损，害怕他人看
不起自己。心理安慰的主要作用，是告知脆弱的心灵：大家还尊重你。其实，如果内心真正
强大，能够将自己的能力和内心认知匹配，有着坚定的目标。一切挫折都不会导致内心出问
题。

** Jan. 25, 2022
对任何人和事，都要保持一定的距离。曾经的两位老师，以为是自己的全部世界，到最后才
发现，俩人都早已离我远去。当时，我觉得可以牺牲所有为他们服务，其实他们并不需要。
除了感动自己，没有留下任何的痕迹。

** Jan. 15, 2022
活的通透和谦虚谨慎并不相悖。通透表示不在乎世俗的追逐，而谦虚却是永远值得保留的态
度和品格。

* 2021 (13)
** Dec. 04, 2021
学识不够的时候，容易对一件事妄议。比如关于孟子，中间有一段时间觉得“当时尚有周天
子，何事纷纷说魏齐”，批评的很有道理。现在才明白，当时的封建传统，孟子是不能僭越
直接面对周天子的。所以，谦虚谨慎，真的是要牢记于心的。可以发表意见，但不能轻易做
结论。

** Oct. 27, 2021
类比起的作用是通过一种相对简单或者形象的方式帮助理解一件事情，但很多人都把类比当
做了因果。实际上，类比的两种事物，毫无逻辑关系。

** Oct. 26, 2021
如果一个单位，能力较低的人反而能取得更大的“成绩”，就必须首先检查这个“成绩”的含金
量。如果含金量不足的“成绩”反而得到更多的赞赏，就赶紧离开这个环境。否则，会让你陷
入极度痛苦却又无法自拔的境地。凡是劣币驱逐良币成功的地方，都要尽早离开。

** Oct. 23, 2021
一定要清晰每件事的边界，甚至一个人做事的边界。如果在一个方面做的好，并不意味着要
把所有的其他面都展示给外界看。这样通常都会适得其反，甚至把那好的一面都抹杀了。

** Oct. 13, 2021
不要迷信任何一个人，包括导师、专家，甚至是该领域的杰出专家。我曾经很长一段时间，
唯孙老师马首是瞻，不敢有一点反对。其实到头来，害了自己，也害了他。而最后 ，他也
并不真心珍惜这唯一的曾经唯命是从的弟子。

** Sep. 28, 2021
人们常常把工具当成了目的，本来只是想要一个孔，结果在追求打孔的锤子上越走越远，把
锤子设计得越来越精巧，而忘记了那个孔是什么。

** Sep. 22, 2021
货币的主要目的，是作为交换的中介凭据。因此，增加货币，可以笔刺激交换的频次。如果
经济发展了，货币量没有增加，交换就会收受到影响。这就是随着经济的发展，货币总量是
不断增加的主要原因。

** Sep. 15, 2021
真正做出实用的产品，才是王道；通过所谓的关系、资源、人情，都只能昙花一现。而实用
的产品，并不一定必须是所有都领先的，关键在于实用。

** Sep. 10, 2021
时刻保持谦虚的态度，主要目的是让自己不会由于狂妄而忽略重要的细节。时常反省自己，
可以更能保持清醒的状态。

** Sep. 09, 2021
Wherever there is judgment, there is noise---and more of it than you think.

** Sep. 08, 2021
短平快的文章和视频，很难让人有所真正的收获。主要原因在于缺乏逻辑性。但是，这些快
餐文化很有粘附性，容易使人上瘾。所以，必须强力地克制自己，去汲取真正的知识。

** Sep. 07, 2021
产生一个观点是不容易的，虽然不要固执地维护，但也需要坚持。谨慎地提出一个观点，认
真地思辨，反复地权衡，努力纳入更大的思维体系，然后，全力以赴地贯彻。

** Aug. 28, 2021
知识一定要用自己的语言重新表述，并尽量形成文字，这样，才能发现是否真正理解和掌握
了它。凡只是听一听、看一看，就以为明白了道理，实际都是自欺欺人。

* 2020 (6)
** Nov. 04, 2020
哲学考虑的是无法科学界定的问题。比如，什么是公平，什么是善，什么是幸福，什么是美。
凡是可以量化定义的问题，都属于科学解决的范畴。哲学与艺术的区别在哪里呢？

** Sep. 06, 2020
任何要求限制在 10 分钟以内的演讲、报告、汇报等，都不能自由发挥，一句废话也不能有。
铿锵有力、抑扬顿挫、节奏明快。如果是 30 分钟以上的演讲，则尽量平和、风趣、幽默，
语速尤其不能快。

** Aug. 30, 2020
我对于平庸是难以忍受的，因此一直以来不满足于一般的科研工作。但是我最大的问题是没
有坚实的基础，不能真正地批判那些无足轻重的研究，同时不能找到更好的方向。

** Jul. 12, 2020
#+begin_quote
每个人的生活都是一条通向自身的道路。每个人的真正职责只有一个：找到自我。然后在
心中坚守一生，全心全意，永不停息。所有其他的路都是不完整的，是人的逃避方式，是对
社会角色的懦弱伪装，是随波逐流，是对内心的恐惧。

—— 黑塞
#+end_quote

** Jun. 26, 2020
由于任正非说要重视基础科学，特别是数学，现在社会上从官员到普通老百姓都开始这一论
调。本来是一件值得欣喜的事，但我并不看好。首先各级官员并没有真正明白基础科学是什
么，目前只是人云亦云，政治正确而已。其次，社会是没有耐心的。当基础科学不能带来可
见的经济进步时，他们就会马上弃之若履。

** Apr. 03, 2020
正如市场不是社会主义与资本主义的区别一样，民主和独裁也不是区分好政权与坏政权的标
志。公开透明的信息传递，相互监督和制约才是做出正确管理的保证。

* 2019 (1)
** Sep 27, 2019
我曾经依靠苦学积累了一些知识，然后击败了一般普通人，就以为自己高人一等。殊不知我
是缺乏创造力的，那些“背住的知识”，没有建立起创造的网络。我实际上错失了上升一个层
次的时机，沉湎于自我营造的虚幻聪明感觉里。

* 2018 (4)
** Nov 10, 2018
一件事，如果想清楚了需要去做，就一定认真去做。否则，就放弃。勉强去做一件事，又不
认真细致，既花费时间，结果一定不好。

不要寄希望于运气，好运气一定不会永远眷顾。一旦运气不在，又不认真做，总有一次会让
你后悔。而且，悔之又悔。

** Jul 13，2018
#+begin_quote
不能因为输一个球就想放弃一场比赛，然后要求重新开始。

——— 吴军
#+end_quote

我从小就缺乏承受压力的能力，当一件事做得不顺利的时候，就想着放弃然后重新开始。表
面上看是追求完美，实际上就是缺乏信心和耐力。一场羽毛球比赛有 21 个球，为什么输了
一两个就马上想放弃呢？

** May 12，2018
人一取得某个成就，就容易膨胀，觉得自己无所不能，非常优秀。井底之蛙的感觉，会蒙逼
双眼，看不清自己的短处和未来。特别的，这种内心深处散发出来的自满和骄傲，会让旁人
非常反感，而自己还不自觉。谦虚谨慎，的确是不能忘记的。该展现自己才华的时候，要充
满自信。一旦在某个特殊方面展现完了，就必须保持谦虚，言谈举止，都不能过份。君子之
行，温文尔雅。

** May 05, 2018
我们太习惯于类比的方式来解释问题，虽然这容易让人理解，但用久了我们常常会忘记这只
是类比，而不是真正的因果逻辑。比如，木桶理论说最短的木板决定了桶能盛水的最大值。
常用来说明，人不能有明显的缺点。但是，人毕竟不是木桶，人能成功也和木桶装水是不一
样的概念。缺点是否就是短的木板，也只是说明而已。可是，我们觉得木桶装水确实由最短
的木板决定的，因此就想当然认为人的成功，也不能有明显确定。这是什么逻辑呢？

* 2017 (9)
** Dec 4, 2017
-   汇报陈述要抓住重点，脉络清楚，逻辑清晰。不能一开始就陷入细节。
-   演讲和座谈是不一样的，演讲可以有肢体语言，座谈就切忌手势太多。因此，一定要区
  分不同场合。

** Oct 26, 2017
-   试图同时做两件以上的事情，是万恶之源。
-   尽量不要频繁切换进程，一次把一件事情做好。

** Oct 16, 2017
如何提高科研
- 尊崇学术的氛围 （尊重和引导）
- 创造研究的环境 （服务）
- 不要过份依赖奖惩

** Sep 21, 2017
学习一样新的东西的时候。怎么也抓不住重点？经过一系列课程的学习，才慢慢发现，各个
方面学习的有机联系，才知道它们是辩证统一的，虽然一开始，还是觉得知识零散，不系统，
有可能，还是碎片化的，但是学多了，才能发现他们之间的有机统一，才能发现它们之间的
共同点是什么，侧重点是什么，才能抓住主要的问题，才能抓住核心的思想。因此，学习是
一个渐进的过程，不能指望一开始，就一下子掌握，那样，只会一头雾水，两眼茫然。

** Apr 27, 2017
-   AIM ABILITY ATTITUDE
-   AIM：目标、定位，想做什么
-   ABILITY：自身能力，可以做什么
-   ATTITUDE：态度，以什么样的状态实施

** Feb. 11, 2017
一定要明白，最重要的是解决问题。知识也好、能力也好，都只是辅助的工具。不要本末倒
置，把学习工具本身当成了目的。因此，明确问题是第一步，找到解决问题的方法是第二步，
然后用各种方法来解决它。

** Feb. 04, 2017
一些人以“允许少部分人先富起来”为名，强行增加科研的奖励，这是不合理的。一部分人先
富起来，并不是将另一部分人的收入强行拿走，转入少数人的手里。而是将总量增加，允许
做贡献的人多拿一些。举例来说，如果两个人分 100 元，各拿 50 元，这是公平。如果一
个人拿 30，另一人拿 70，在同样的贡献情况下，这就是不公平。但如果其中一个人通过自
己的劳动，将总量变成了 200 元，然后他拿 120 元，另一人拿 80 元。虽然两人的收入不
一样了，但仍然是公平的，而且是真正做到了少数人先富起来。

教学是非常重要的，但我非常反对纯粹的教学，没有研究思想引入的书本教学法，是非常低
级和没有效果的。诚然，书本知识的传授在传统教育中曾经起过非常重要的作用，但是，如
果没有新技术的引入，传统的教育根本不知道从何改起。例如，吴志坚教授就举例说，我们
当年都学过如何手工进行开根号运算。这项技能被认为是学生应该掌握的基本技能之一。但
是，现在哪个学校还在教授这个？由于计算机的快速普及，一般的人已经不需要知道如何开
根号，这一点也不影响我们学习其他的知识。因此，现在我们在高等数学课堂里，花很多时
间教授积分的各种技巧，常常抱怨课时不够。可是利用 mathematica，我们可以一瞬间地求
出任何函数的积分（至少是数值定积分）。我们为什么还要学习积分的各种奇淫巧技？至于
哪些技能可以被取代，哪些技能是必须掌握的，这都不可能通过纯粹的书本知识来区分。现
代研究的各种最新技术才是帮助我们辨别的工具。

** Feb. 02, 2017
太多的短平快文章，几乎影响了我的思维。一定要看经典，而不是心灵鸡汤。一本书没有看
完之前，不要贪多去看其他的书。

转了一圈，发现还是 Emacs 编辑器好用，LaTeX 处理文档好用。似乎这两个软件都是我在
上个世纪就开始学习的，在博士刚毕业的时候还花了很多时间熟悉和运用。可是后来，又渐
渐放弃了它们，觉得有更多更好的软件可以用。现在想来，学习的成本太高了，因为花了很
多时间学习，结果却并没有大规模使用。应专注于内容，而不要太在乎流行形式。

我还是有程序员的思想，任何事情，只要有重复性的部分，就想着写程序来代替。其实，这
样的思想，用 Emacs 是最好的。

** Feb. 01, 2017
如果一篇文章的观点没有被自己真正掌握，那么读再多的书也是没有用处的。现在的信息太
多，网上流传的文章多是鸡汤。盲目地往 evernote、wiznote 上存文章，只是满足自己炫
耀的心理而已。Feynman 早就说过，知道一个事情的名字和明白一个事情的本质，有多么大
的区别。

从此之后，不要随意阅读文章，要尽量阅读精品，特别是要被自己理解、记忆，融入自己的
思想，能够用自己的语言描述，这样，才是真正地理解了一个观点。

我的表达现在越来越差，似乎不能用文字的方式完整清晰、有理有据地表达一个观点，这似
乎是写作太少的缘故。因此，我要加强书写的能力。更关键的是，大脑对于某个观点或者思
想没有清晰的认识和判断，虽然读了很多书和文章，但都没有真正转化成自己的思想，因此
很难用自己的语言表达出来。记住：贪多嚼不烂。

* 2016 (13)
** Nov. 13, 2016
我 2009 年刚来西华大学的时候，虽然心态很幼稚，能力很欠缺，但想着要把理化学院做好。
因此，无论预见什么困难，我都有信心去克服。现在，我完全没有想把西华大学的科技工作
做好的勇气和信心，更没有提升西华大学科研工作的信念和理想。所以，如果我接手科技处
的工作，是做不出成绩，也不会取得明显的效果的。既然如此，我为什么还要浪费时间呢？
没有成功的信念，做事就不会成功。

** Nov. 07, 2016
书太多了，也不是件好事，因为我着急的想把他们都看完，越着急越看得不认真，很多东西
都没有理解透彻。所以贪多嚼不烂，看书还是要细致认真慢慢地阅读。

** Oct. 26, 2016
之所以人们经常在讨论中变换立场，或者讨好上级，或者畏惧权势，大多都因为心中没有准
则。在讨论一个议题之前，自己必须有一个大致的判断，而且必须符合自己的长期价值观。
这样，才不会随波逐流。当然，如果事先没有明确的判断，就应该多听他人的观点。

在表达自己的观点之前，无论如何应该之前听清楚其他人表达的内容！

在任何时候都应该保持谦虚的态度，说话要不卑不亢，有礼有节。这样，大家才会真正的尊
重你。否则，就会适得其反。你稍微表现出一些骄傲的神色，大家就会厌烦你，即使你真的
很有才能，真的能完成一些事情，大家仍然不会尊重你。

** Oct. 24, 2016
成功确实是某一阶段的事情。今年上半年，C罗赢得了欧洲杯，也赢得了欧冠。而梅西，失
掉了欧冠，又失掉了美洲杯。当时的舆论评价梅西已完全失去了机会，在走下坡路。可是新
赛季开赛以来，梅西还是那么勇猛，而 C 罗的进球数却大幅下滑。回想三个月以前和三个
月以后，确实是千差万别。所以，永远要记住，成功只是一阶段的事情。不放弃，永远坚持
做下去，才能够真正的获得成功。一时的评价，也许会扰乱你当时的心情。长远的看，所有
的外界评价。都是无关紧要的。

一方面，需要他人的认可，另一方面，又要装着不在意别人的评价。时间就在这样左右为难
中纠结着。实际上，人活着到底为了什么呢？

** Oct. 16, 2016
一个组织或者系统，从组织者到最底层的员工，都应该有统一的目标。虽然每个人的能力、
想法、利益诉求不一样，但至少都应该认同一个共同的目标和核心价值观。否则，系统容易
陷入各自为战的混乱之中。

现在，西华大学最大的问题是没有统一的目标和思想。教学好的认为教学最重要，科研好的
强调学术才是高校的根本，学工系统认为学生的全面培养才是重中之重……。不能说这些看法
没有道理，但是在一个需要全面追赶的落后单位里，必须有一个龙头带领。轻重缓急，主次
分明。不是说其他的事情不重要，而是因为思想不统一容易造成政策的执行混乱。

** Oct. 11, 2016
做学问就是要不停地追问为什么，直到不能回答为止。这样，就可以发现自己的基础到底有
多劳，自己不懂的地方到底卡在哪里。如果一个问题不能用自己的语言来回答和描述，就表
示这个问题自己并没有真正掌握。

** May 26, 2016
“没有任何一个选择是绝对正确的，我们能做的是让我们的选择变得正确 ……”

** May 12, 2016
#+begin_quote
“一切的绝望，都是从做自己不擅长、不愿意、不认同的事情开始的。爱情是，工作是，人
生也是。不是打心眼儿里认可的事是绝对不可以做的，因为一旦做了，人就会长出一种鬼鬼
祟祟的气质，然后这一辈子就完蛋了。”

 这不是我说的，是一个做木偶的中国姑娘说的，我很喜欢。正所谓凡夫畏果，菩萨畏因，
 在此一并摘录。

--- 磊子
#+end_quote

** Apr 23, 2016
做好一件事情，除了自己有想法有干劲以外，最重要的一环就是有一个配合良好的团队。团
队的组成不能随意拉郎配，不能凑人数，必须要有统一的思想，有相互配合的合作方式。因
此，挑选团队，重中之重。

** Mar 27, 2016
"君子不立危墙之下"，当一个单位整体处于下坡之时，如果不能改变它，就应该及时远离它。
否则，这个群体的整体下滑，必然导致道德准则的偏差。迟早自己也会变成当初曾经讨厌的
人。"如果不能按所想的方式去生活，迟早就会按照所生活的方式去想问题”。

** Jan 24, 2016
读书，是为自己有判断的能力，选择的权利。

** Jan 20, 2016
如果一件事情不是自己真心喜欢做的，迟早都会丢弃。所以，一定要想好，不能因为别人喜
欢，自己就盲目地去追求。如果不能投入自己的热情和精力，只是痛苦地敷衍对付完成，这
样的事情有什么意义？

** Jan 1, 2016
看书只是为了明白道理，但要把这些道理联系起来，不能支离破碎，毫无关联。读书多了，
就会发现所谓的科学分类，文科理科，都是人为制造的。

这个世界上，大多数人都是在搭便车。领头的人自然是要付出更多的心血和努力，也许最后
会得到更多的回报。但也经常付出远远超过收获。必须容忍那些搭便车的人，他们只是普通
的市民而已。想明白了这些，就不会有愤愤不平、觉得吃亏了的感觉。

* 2015 (18)
** Dec 28, 2015
一定要做与人直接相关的研究，比如医学健康，环境污染治理等，从机理上搞清楚研究的问
题。不要再做太虚幻太理论的课题了。

** Dec 27, 2015
-   能否做一个类似慕课那样的网络教学平台，内容不限于物理，而是趣味自然科学之类的。
-   视频最好，伴随文章，加上电视台等多个媒体
-   关键是内容，认真考虑受众群体，到底要达到什么目的
-   发挥自身的优势和强项

** Dec 5, 2015
-   重要的不是改变，而是适应。如果认同某一个群体的价值观，则融入并发展；如果不认
  同，则远离，越早越好。
-   永远不要为了掩饰或者证明，而对自己进行伪装。该说的话不说，该做的事不做，不该
  说的违心去说，不愿做的违心去做，到最后，还是只有后悔。

** Nov 14, 2015
我越发感到我缺乏系统解决一个问题的能力，或者说我几乎不能有效地执行一个项目。随心
所欲地面对一个问题，只是从表面肤浅的第一感觉出发提出解决方案，一般是行不通的。

** Nov 4, 2015
基础研究，是和全人类比，因为没有版权，只要一个人做出来，全社会就能知道。因此，如
果一项基础研究，不能争第一，则几无价值。应用则不必第一，因为只要解决了一个实际问
题即可。从本质上来说，很多应用研究其实并不是研究，而真的是应用而已。

我的资质并不算太出众，选择基础研究，与全世界的精英竞争，是否明智？

** Oct 25, 2015
很多情况下争论来自于沟通不畅，争论的双方并没有理解对方表达的是什么。例如，学校提
倡好文章，然后一些人反对。除去混淆视听专空子的人外，这些争论的人没有在一个层面上
讨论。反对的人觉得更重要的是做出实际有用的工作，而不是简单的发表一些文章。可提倡
文章的一个重要原因是先鼓励大家进行科学研究，创造一个学术氛围。因此，两方的人都觉
得自己是正确的，鸡同鸭讲，乱打神仙帐。下面的人趁机浑水摸鱼，一塌糊涂。

** Oct 20, 2015
平和是非常难以做到的事情，包括了心态平和，语言平和，不卑不亢。谦谦君子，温润如玉。

** Oct 5, 2015
如果说一切均是虚无（包括宗教），一切都没有对错。那么，社会公德代表什么意思？我们
觉得有些事不能做，不该做，到底来源于什么样的力量？教育的根源来自于哪里？是自然法
吗？

** Sep 26, 2015
每个人都喜欢坐享其成，然后推卸责任。不能老顾及他人的感受，一味做老好人。重要的是
解决问题，完成任务。

** Sep 19, 2015
从网上下载了很多书，结果花了许多时间，浪费了精力，大多效果不好。当决定买一本书时，
比较来比较去，非常担心物不所值。钱，还能帮助我们辨别价值啊！

** Sep 14, 2015
人都是生活在某个秩序和等级中。比如科研，就有各级院士、杰青等组成一个庞大的等级；
比如管理，就有校长、院长等再构成另外一个组织。每一个组织有自己的运行方式，如果想
两者都兼顾，几乎是不可能的。如果想在更多的组织中轻松自在，简直就是天方夜谭。我的
问题是，并没有明确自己到底想在哪一个组织中存在。所以，在一个组织里反而想着另一个
组织的好处，结果都没有做好。

因此，明确自己的目标，才是最重要的事情。

** Aug 19, 2015
1.  体制
1.1.  理学院坚持分岗制度，顶住压力，扶持年轻人。所有获得基金的人都是 09 年后进入学
院的
2.  领导核心
2.1.  学校的领导层都有自己的思路。绝大多数思路斗没有好与坏之分，而是能不能有效地
坚持和执行。

** Aug 18, 2015
做事情，首先要明确目标，也就是发现要解决的具体是什么问题。不能模糊地就想解决虚幻
的问题，要清晰化。必须描述清楚问题的表现，以证明这些确实是问题。再分析问题产生的
原因。最后找出解决办法。We have to find what the real problems are.

** May 28, 2015
为什么物理公式中会出现复数？能量的虚部代表什么涵义？不能只把复数仅仅当做计算的工
具，在量子力学方程里出现的波函数，竟然是一个复数量，这是十分令人惊奇的。以前看书
时，似乎没有想过它的物理意义是什么。今后一定要认真思考这个问题。

** May 3, 2015
一定要认认真真读书。网上的及时新闻，实际上没有多大的用处。在我这样的年龄，最重要
的是真正明白理解道理，然后可以转化为自己的思想，并可以用于下一次的创造。创新，只
有创新，才应该是我现在考虑的重点。

** Apr 13, 2015
要真实地明白自己内心需要的是什么，对一切根本上就不愿意的事情说不，无论它来自哪里。
这么多年以来，我太多地隐藏自己的想法，不知道什么是拒绝。从现在开始，要认真探究自
己的内心。要去哪里，想要什么。

** Mar 15, 2015
我现在所做的科研工作，只是在重复地验证量子力学在原子分子领域是多么的正确。每一次
计算结果与实验的比较，都只是再一次地复述。理论工作的意义重点在哪里呢？应该是预测
啊。解释只是某一个理论刚开始的时候需要考虑的侧重点，当一个理论可以写进教科书时，
重点应该转为预测。

** Mar 8, 2015
-   不要担心需要的工具没有了，因为真正需要的东西要么会变得更强大，要么会被取代。
  因此，要把注意力放在如何创造上。
-   以前常常担心自己领悟的知识被其他人窃取，所以总是掖着藏着，不愿意让人知道。实
  际上这是小农思想，嫉妒心强的表现而已。现在应该知晓，如何把自己明白的道理有效地
  传播出去，才是最重要的。
-   观点的形成、证据的收集、数据的分析、最后优美的文字表述，是写作的基本，缺一不
  可。
-   我以前常常只注重最后的思考结果，认为这才是最本质和重要的。但是，为了要说明一
  个观点，必须有强大的论据支持才行。因此，数据和实例是如此重要。当你忘记结论是什
  么的时候，只要有正确的逻辑分析能力，加上证据，你自然会得到正确的结论。在说服他
  人的时候，这就更加重要。

* 2014 (8)
** Jun 15, 2014
对研究实在是找不出方向，几乎都在读书中打发时间。日子就像有回到了 02 年左右，百无
聊赖，然后疯狂看书。对于物理和程序，兴趣都变得没有那么浓厚了。

一直都在逃避吗？因为没有找到兴趣点。商业？科学？技术？管理？还是迷茫。

单纯的开会是不可能解决问题的：
1. 必须有明确的议题；
2. 会前必须有准备和思考，与会者必须清晰开会的目的，并有自己的见解和观点，以及说
   服他人的论据；
3. 会中要听取每个与会者的观点，否则就没必要请他参加；
4. 要坚持自己的观点，但不能固守方法。如果发现明显漏洞，就应该修正；如果觉得不能
   此次会议达成共识，最好放一放；
5. 会议要有清晰准确的记录，以便后查；
6. 一定要落实执行者，并明确检查的具体时间；
7. 会议结束和执行了一段时间后，最好有总结和分析，对利与弊都应该认真地反思。

** Jun 10, 2014
看一个人确实不能短期内轻易下结论。前几年觉得曾义很听话，做事情很细致认真，比吉驭
嫔强很多。可是近一段时间以来，发觉她也开始斤斤计较，小肚鸡肠，甚至有些自私自利，
做事情也没有那么细致认真了。是她变了还是我变了？亦或是逐渐现出了本质。

** Jun 09, 2014
我发现自己越来越容易暴躁和激动，说话的预期、语速都不平和。反映出情绪的不稳定和不
宽容。当说话过快，观点偏激时，容易给人印象是草率下结论，即使事实并不如此。宽容、
平和，到现在这个阶段了，已经不需要通过争论来显示自己的优秀，过强的咄咄逼人，反而
适得其反。

** Jun 08, 2014
- 为什么 R-matrix 方法如此流行，一个重要的原因就是 UKRmol 软件包的开源。当其他小
  组的人可以自由获取源代码，并能应用到不同体系时，基于 R-matrix 的应用就会蓬勃兴起。
  相反，另两个重要的方法：complex Kohn 和 Schwinger MC，公式虽然大家都知道，但计
  算软件包，只局限于创始人手里，他人无法获取，更不能应用。这就大大减少了基于
  complex Kohn 和 SMC 的推广和应用。
- 我似乎只习惯于线性思维，喜欢用文字和线性层次来整理思路。对于图形和表格，我用的
  极少，仅仅是为画图，或者只是展示给别人看。而我自己在思考问题时却不怎么用图表，
  这或许是我的一个大 bug。

** Jun 07, 2014
现在反思这几年做管理的不足：
1. 没有将追求学术的理念贯彻开来。教师的职业道德素养并没有建立，或者广义来说，团
   队文化没有建立推广。

** Jun 06, 2014
没有什么方法是放之四海而皆准的。一段时间，我以为 R-matrix 方法在 e-mol
scattering 领域已经一统江湖了，但认真地学习了大量资料后才发现，这只是一个幻觉。
Complex Kohn 或者 Schwinger Multichannel 方法也是如此。我曾经以为要丢进历史垃圾
堆的 Linear Algebraic 方法，也是有它的长处的。特别是 DSG 这样的 local model
polarization 也不是一无是处。

** Jun 05, 2014
- 我现在对苹果的产品兴趣并不大了，有时都不想被苹果的东西束缚住，但很多功能又被依
  赖。回想 05-06 年的时候，背着 powerbook pro 在川大校园里自由自在，真是怀念啊。
  我追求的难道只是与众不同？
- 系统地学习某一理论，不仅仅是掌握该理论的重要途径。通过这一过程训练，对整个框架
  都有重要作用。e.g., 学习 R-matrix 理论，不仅可以掌握该模型方法，对整个
  scattering theory 的理解都是有重要帮助的。
- 归根结底，基础知识的学习和理解都是非常重要的。你可以发表一两篇文章，但要想做出
  重要的工作，则必须有深入的理解。

** Jun 02, 2014
看了很多文献之后，才发现 B. I. Schneider 真是了不起，电子与分子散射的几大流行方
法：
1. Linear Algebraic Method (LAM)
2. R-matirx
3. Complex Kohn variational
4. Schwinger Multichannel Variational

他对前三个方法都做出了开创性的贡献。Optical potential 也是他利用 projection
operator 方法推导出来的模型。还有许多实际的计算方法和技巧。在中国，一定是资深院
士水平。可是，他好像并不是美国的科学院院士。

* 2013 (1)
** Sep. 09, 2013
从网上下载了很多书，结果花了许多时间，浪费了精力，大多效果不好。当决定买一本书时，
比较来比较去，非常担心物不所值。钱，还能帮助我们辨别价值啊！
