:PROPERTIES:
:ID:       AFA8305D-B0C0-41D7-A3DC-6369D5A2DE47
:END:
#+title: 读后感
#+filetags: :progress:

读了很多书之后，经常忘记一本书讲的是什么，然后重复读。过了好一会儿，才反应过来，读过，不值得重读 :-(

* [[id:D9D309DB-6260-454A-88A8-AB4D7D65EE25][评分标准]]

* books (136)

** 五星 (22)
*** Donald E. Knuth
**** The Art of Computer Programming I
**** The Art of Computer Programming II
**** The Art of Computer Programming III
**** The Art of Computer Programming IV
**** The Art of Computer Programming V

此套丛书，编程算法的经典著作，什么时候都值得深入读。都有简称了：《TAOCP》

*** Richard P. Feynman
**** The Feynman Lectures on Physics I
**** The Feynman Lectures on Physics II
**** The Feynman Lectures on Physics III

费曼讲物理，是我一生的最爱。

*** 金庸
**** 飞狐外传
**** 雪山飞狐
**** 连城诀
**** 天龙八部
**** 射雕英雄传
**** 白马啸西风
**** 鹿鼎记
**** 笑傲江湖
**** 书剑恩仇录
**** 神雕侠侣
**** 侠客行
**** 倚天屠龙记
**** 碧血剑
**** 鸳鸯刀

飞雪连天射白鹿
笑书神侠倚碧鸳

每本书我都看了至少 5 遍以上。

** 四星 (6)
*** Donald E. Knuth
**** Concrete Mathematics
此书是《TAOCP》的简化版，文笔很好，也值得反复阅读。

*** Walter Isaacson
**** Steve Jobs
我觉得这是 Isaacson 写的最好的一部人物传记。对于乔布斯的一生和思想，以及创造的产品，改变的社会，此书都是非常好的了解资料。值得多次阅读。

*** 顾衡
**** 顾衡好书榜
此书打开了我的视野，得到音频我都听了三遍以上。对历史、哲学、政治等话题的讲解，顾衡能做到深入浅出，非常了不起。值得多次阅读。

**** 顾衡讲好书
此系列是每周带领大家读一本书，讲得也很好。但是由于经常东一本西一本，没有《好书榜》里的专题系列讲解得深入。

*** 吴军
**** 计算之魂
此书是关于编程算法的通俗讲解读物。吴军的数学基础很好，写书也能做到深入浅出。

**** 浪潮之巅
关于科技大公司起伏沉沦的发展史，值得反复阅读，以明白科技、商业在人类发展史上的作用。对于个人来说，会极大开阔视野。

** 三星 (23)
*** Anil Ananthaswamy
**** 双缝实验和量子力学：一个简单的光学实验如何串起不确定的量子世界与确定的经典世界 
关于量子力学，最新的实验和解释，我们大部分都不知道。学校里的量子力学教科书，还是只有计算、计算、计算。双缝干涉实验，是量子力学最重要，也是最本质的实验之一。关于最新的所有量子力学解释，都可以从中找到对应的实验。

物理学，必须要从实验出发，思考和创建理论。

*** Chris Miller
**** Chip War / 芯片战争
此书详细地介绍了芯片从二战开始直到今天的发展历史，阐述清楚了为什么芯片在当今社会如此重要。读者更加了解了当今国际科技战争的本质，包括由于台积电的原因，台湾海峡为什么成为了全球重视的焦点。

参考文献都有几千个，是科普类作品的学术写作典范。

*** Etienne Berbard
**** Introduction to Machine Learning
此书详细介绍了机器学习的常见概念，并用 wolfram 语言进行了演示。不是一般的泛泛之谈，但也并不深奥。对于初学者，是非常好的入门书。

*** Ian Goodfellow & Yoshua Bengio & Aaron Courville 
**** Deep Learning
深度学习的权威教材，如果只读一本关于深度学习的书，想要有深度的话，就读这本。

*** Jeremy Howard & Sylvain Gugger
**** Deep Learning for Coders with fastai and PyTorch: AI Applications Without a PhD
关于 DL 和 PyTorch 好的入门读物，如果想深入了解，可以多读几遍。

*** Leonid B. Shifrin
**** Mathematica programming: an advanced introduction
关于 mathematica 使用的高阶技巧：functional and rule-based programming，本书有非常细致的讲解。唯一的缺点就是没有考虑最新版本的数据处理。

*** Michael Nielson
**** Neural Networks and Deep Learning
对 NN 和 DL 的基本原理有深入浅出的讲解，尤其对于 backpropagation，推导很清晰。对于 CNN、RNN、Transformer 等网络结构没有过多描述。适合作为入门级的了解神经网络的读物。

*** Neil deGrasse Tyson
**** Astrophysics for People in a Hurry / 给忙碌者的天体物理学
非常好的科普读物，让人觉得宇宙如此美妙，自己又如此渺小。和宇宙相比，哪里还有什么真正值得忧虑的事呢？

*** Robert J. Chassell
**** Programming in Emacs Lisp
对于不熟悉 Emacs Lisp 的读者来说，此书深入浅出地讲述了如何用 Emacs Lisp 来编程---连编程的基本思想都顺带讲解了。可以作为 Elisp 的入门教材。

关于 Elisp 的执行顺序和后台原理，这本书也提到了，对于初学者来说，相当友好。

*** Russel Kirk
**** 美国秩序的根基
非常严肃的政治学读物，详细介绍了美国底层的运行逻辑。不了解美国历史和政治来源的人，很容易误解美国表现出来的各种思潮。这本书正本清源。但和林达的书比，太过于枯燥。不过，比林达的书要权威和严谨得多。

*** Sebastian Raschka
**** Build a Large Language Model (From Scratch)
对于如何构造 LLM，这本书给出了 step by step 的答案。更为难得的是，既没有在细枝末节上啰唆，又讲清楚了重点。值得认真阅读。

*** Sebastian Raschka & Yuxi Liu & Vahid Mirjaliti
**** Machine Learning with PyTorch and Scikit-Learn
1. 学习 ML 的入门读物，值得一读。
2. 讲解了很多原理，深入浅出

*** Seth J. Chandler
**** Query: Getting Information from Data with the Wolfram Language
这本书讲解了如何利用最新的 Association 结构和 Query 操作来进行数据处理。值得多看几遍，掌握 wolfram 语言的精髓。
但这本书确实写的不友好，有些技巧，太过于小众了，有炫技的味道。不适合作为一本教科书。

*** Stephen Wolfram
**** 万物皆计算
沃尔弗拉姆的洞见，实在是值得反复思考。这本书是他本人博客的一些选集，其中关于wolfram软件的发展，值得反复阅读。有些文章，例如生平或者函数的命名，看一遍就行了。本来想打四星，但看完之后，发现，偶尔看一下可以，反复阅读这本书就没有必要了。

还是直接去看沃尔弗拉姆的博客比较好。

*** Walter Isaacson
**** Elon Musk
关于马斯克的传记，也许这是到目前为止最好的一本，但没有 Isaacson 写的乔布斯传记好。值得一读。
**** The Innovators
关于一些天才的介绍，他们是如何影响并改变数字世界的。

*** Wolfram Documentation Center
**** [[https://reference.wolfram.com/language/tutorial/NeuralNetworksOverview.html][Neural Networks in the Wolfram Language]] 
非常好的用 wolfram 代码构建/训练/使用神经网络的入门级教材。果然 Wolfram 自己的官方网站出品，都是精品。

*** Yuval Noah Harari
**** 智人之上：从石器时代到 AI 时代的信息网络简史 
这本书的前半部分很好，在《人类简史》的基础上，进一步提出非物质的叙事结构，可以深刻地改变人类社会。但是后半部分，把人工智能引入进来之后，本意是想说 AI 也可以形成新的叙事结构，从而影响人类。但作者对于 AI 确实理解得不够深刻，所以欠缺说服力。

*** 金泰
**** 英伟达之道
英伟达能成为第一个超过4万亿市值的高科技公司，自然有其独到之处。其创始人黄仁勋也是技术和商业集合的代表。目标明确、技术扎实、商业眼光独到、扁平化管理........。成功了的企业，当然是做对了事情。

这本书比一般的企业成功学鼓吹书要好一些，作者做了大量的访谈，有公司内部的，有竞争对手的。因此，有一定的说服力。

*** 李一冰
**** 苏东坡新传
关于苏东坡的传记，有很多版本了。林语堂的最为出名，但也很脸谱化，勾勒了一个大致的形象。这本书，严格考证了苏东坡的生平，以及所有流传于世的作品。

苏东坡果然是中国传统知识分子的最爱，但是，老天爷对他也的确残忍。文坛领袖，晚年竟然在海南这个认字都是一件奢侈的环境里居住。这是何等的悲哀啊！

*** 钱穆
**** 中国历代政治得失
关于中国古代，是否有先进的政治制度，钱穆是持肯定态度的。对于汉、唐、宋、明清的政治运行方式，钱穆给出了清晰易懂的介绍。虽然对于“失”的分析，我个人觉得还没有触及本质，但对于整体的了解，是很有益的。

*** 吴翰清
**** 计算
不仅是关于计算，连数学的发展史都有不同程度的描述。作者明显是学术派出身，很多数学证明都自己做一遍。对于计算在现代科技中的作用，尤其在 AI 方面的应用，都是很好的参考。

*** 熊培云
**** 一个村庄里的中国
关于中国的农民，我一直觉得很苦，社会和国家亏欠他们。我们很多的问题，都由个人和家庭消化了。但是，人的同情心和同理心，让我每次读到此类文章，总是感慨人的悲欢并不相同。从一个村庄，了解中国的社会变迁，可以多一些读书人的责任感吧。

** 两星 (53)
*** Ashish Ranjan Jha
**** Mastering PyTorch Create & Deploy Deep Learning models from CNNs to multimodal models, LLMs & beyond
大致讲述了如何在 PyTorch 架构下部署各个 DL 模型的方法。有一定参考价值，但由于没有原理的介绍，所以最好当作一本参考书翻阅。

*** Ben Auffarth
**** Generative AI & LangChain Build large language model (LLM) apps & Python, ChatGPT & other LLMs
此书的第一章对 LLM 及相关概念做了很好的解释，对于初次接触大语言模型的读者来说，非常简介明了。

作为用 LangChain 开发 LLM，全面通俗地快速了解，是很好的入门读物。

*** Dan Heath
**** 上游思维
核心思想，是不能只找到事情的一阶原因，更要找到原因之上的原因，这样，才不会头痛医头脚痛医脚。思想是不错的，但似乎也并新颖。

书中的案例很多，这是一个好的写作方法。但我发现，也有不好的一面，会让事情处理显得简单和幼稚，世上哪有什么一两个方法，就把事情处理得完美的呢？

*** Daniel Voigt Godoy
**** Deep Learning with PyTorch Step-by-Step: A Beginner's Guide
如何用 PyTorch 来编写 DL 代码，这本书有详细的讲解。不足之处在于，代码太繁琐，而原理讲得反而不够透彻。

*** David Kadavu
**** Digital Zettelkasten: Principles, Methods, & Examples
如何做笔记，一直是个难题。这本书给了一些基本的思想，比如如何捕捉临时的火花，如何转入正式的笔记，以及最后变成永久的笔记。但略显简单，作为初次了解的还可以。

*** Jalil Villalobos Alva
**** Beginning Mathematica and Wolfram fro Data Science
对于新数据结构：association 和神经网络有比较清晰的讲解，适合初学者看。
但是，这本书的代码编排实在是太糟糕了，我不得不重新用 wolfram notebook 重新排版了几章。

*** José Guillermo Sánchez León
**** [[/Users/RDS Library/José Guillermo Sánchez León/Mathematica Beyond Mathematics_ The Wolfram Language in the Real World (2754)/Mathematica Beyond Mathematics_ The Wolfra - José Guillermo Sánchez León.pdf][Mathematica Beyond Mathematics: The Wolfram Language in the Real World]] 
本书介绍了除了基本的数学运算外，Wolfram还能做什么，尤其对于网络数据的获取和分析。但是，作为入门了解可以，深入运用则显得很不够。

*** Michael Wooldridge
**** A Brief History o Artificial Intelligence
虽然作者是有名的专业人士，但 2019 年之前写的所有关于 AI 的书，看来都有点过时了。这个领域发展的如此之快，即使是通识读物，都不能给予很多的启发。当然，对于 AI 的历史，专业人士说的，总还有点靠谱。但对于 AI 的预测和碰到的问题，基本就一半对一半了。

*** Mohamed M. Hammad
**** Neural Network and Deep Learning with Mathematica
用 mathematica 代码演示了如何进行 NN 编程，对于不熟悉 NN，尤其不知道如何用 mathematica 做 NN 的，是一本好的入门参考书。不过，看多了，有点啰唆。

*** Nikhil Ketkar & Jojo Moolayil
**** Deep Learning with Python: Learn Best Practices of Deep Learning Models with PyTorch
讲了一些数学原理，适合了解 DL。但是代码演示太丑陋了，影响了编程学习。

*** Paolo Perrotta
**** Programming Machine Learning: From Coding to Deep Learning
此书深入浅出，把 machine learning 和 deep learning 讲的浅显易懂，非常适合第一次接触机器学习。里面的 python 代码也很简单，不炫耀高级语法，实在是比较友好。

写书和做人一样，能站在对方的角度考虑问题，即使不好，也差不到哪去。

*** Sanket Subhash Khandare
**** Mastering Large Language Models Advanced techniques, applications, cutting-edge methods & top LLMs
对于大语言模型的历史和发展、数据处理、模型原理等，都讲述得非常清晰，有时候觉得太细了。对于初学者来说，是一本不错的入门读物。

*** Savaş Yıldırım & Meysam Asgari-Chenaghlu
**** Mastering Transformers
通过举例，把很多流行的 LLM 如何应用 transformer 架构介绍了一遍。优点是讲了很多概念，缺点是每个部分都不详细。因此，一本书如果想包罗万象，要么就会变成“巨著”，要么就会变成四不像。

*** Scott E. Page
**** The Model Thinker
复杂的世界，需要用模型思维，快速地把握本质。所谓模型，就是有选择的简化。与之对应的思维方式，就是大数据（所有的因素全部考虑进来）。对于人来说，因素一多，就分不清重点。因此，模型思维是十分必要的。

本书讲了很多重要的模型，但很遗憾，作者并没有把这些模型的运用讲解清楚。虽然 Page 是圣塔菲研究所的领导之一，但对于复杂性的讲解，不够大师级别。

*** Sönke Ahrens
**** How to Take Smart Notes
详细介绍了 ZettelKasten 笔记法，对于我设计自己的 Org-Roam 笔记系统很有帮助。缺点是太详细了，符合德国人一贯的严谨风格。但是，试图在一本书里塞入太多的内容---而彼此是可以相对独立的，则没有必要。这本书同时讲解了如何写学术文章，反而把主题分散了。

*** Steven Wolfram
**** What Is ChatGPT Doing ... and Why Does It Work?
Wolfram 讲 ChatGPT 的原理，主要是基本的深度学习和模型的概念。对于初次接触大语言模型，又想知道原理的人来说，此书可以作为敲门砖。我读了两遍，很有收获。但是，也不值得多花时间再读了。

*** Valentina Alto
**** Building LLM Powered Applications
对于如何使用 LLM，这本书有浅显的概述。最大的优点是：解释了很多基本的概念。作为一本入门书，可以翻翻。

*** 安东尼·刘易斯
**** 批评官员的尺度
为什么媒体有这。这本书给出了来龙去脉的讲解，并介绍了优缺点。

如果想了解媒体为什么权力这么的历史，可以读这本书。作者的文字功底很好，讲的通俗易懂，也不啰唆。

*** 邓力群
**** 十二个春秋
一个极左的人士，如何看待 1975-1987 这十二年的中国政治，是有些意思的。对于了解那一段历史，听听不同的声音，还是有好处。

一个顽固的思想，确实对于社会和人民，十分有害。虽然邓力群个人的品质也许超过了一些人，但这种来自底层的极左思想，实在是太有害了。

*** 冯唐
**** 有本事
个人感悟，不值得细看，但贵在一个真实。

*** 郭岱君
**** 台湾往事：台湾经济改革故事（1949~1960）
关于台湾如何从 1949 年的近于瘫痪到如今政治、经济跻身发达国家的行列，原因众说纷纭。这本书归因于几个重要人物的影响：蒋介石、陈诚、尹仲容、严家淦....。至于本质原因如何，大概这本书的主观判断多了一点。可作为海峡对岸的我们，了解那时的台湾历史参考。

*** 江城
**** 历史深处的民国
民国从甲午战争到49年建国，这段历史有很多细节，或者真相，掩埋在了正史的宣传之中。此书弥补了这个缺陷，虽然有些地方有夸大的嫌疑，有作者自己的感情倾向，但总是一个好的补充。

*** 金观涛 & 华国凡
**** 控制论与科学方法论
科普性地介绍控制论，对于建立思维，有一定的帮助。

*** 京夫子
**** 北京宰相
**** 西苑风月
**** 夏都志异
**** 血色京畿
本来想了解中共的一些内幕（关于周恩来、高岗、邓小平等），结果臆想的成分太重。凡是关于历史的资料，必须有可靠的来源，然后自己分析。绝不能猜测只有当事人才知晓的对话、心理活动。这套《京华风云录》太让人失望了。

不过，此书也并不是一无是处。对于了解当时的那段历史，有一些参考价值。作为野史来读，还是可以的。

*** 雷军
**** 小米创业思考
作为一个企业家，我很佩服和尊敬雷军。这本书也是他本人的思想体现，也是小米企业的推广。看-看，对自己的企业很有帮助。

*** 刘晗
**** 想点大事
从法律工作者的角度，科普一下法律的历史和现状。对于了解当今社会的法制现象，有一定的意义。可以翻翻。

*** 罗翔
**** 法治的细节
罗翔关于法律，尤其是刑法（他自己的专业）的个人认识，介绍了一些历史，更多的是自己的思想转变历程。罗翔能够直面自己的内心，承认自己的弱点，在当前的“名人”里，已属难得。这本书可以翻翻。

*** 钱穆
**** 中国历代政治得失
《得失》一书是一九五二年三、四月间，钱穆先生访台北，应邀作一系列演讲，以“中国历代政治得失”为题，分汉、唐、宋、明、清五代，略述各项制度的因革演变，并指陈其得失所在。最后整理付梓成书。用五个典型的中国皇朝治理，提要勾玄地依次讲述了政府组织、选举与考试、赋税制度、国防与兵制等方面，要言不繁，论述精僻。对于深入思考中国为什么是中国，有很重要的启迪。

但或许是后面类似的书多了，更丰富全面的也有。所以，此书作为开创者，有读的意义，但也不需要重读了。

*** 阮一峰
**** 未来世界的幸存者
**** 如何变得有思想？
这两本
书是阮一峰在不同时期的感悟和随笔。20 年前的时候，我曾经觉得阮一峰很有想法，思想有许多独到之处。到了 2024 年再重读，有不过如此的感慨。因此，这两本书，快速翻一翻，就可以了。

*** 桑格格
**** 小时候
这本书就是简单的对过去时光的记忆，有些大概是真实的，很多大概是想象的。桑格格的文笔很幽默，第一次看的时候，觉得还有一点温暖的感觉，以至于 10 年后我竟然又重读了一遍。但是啊，重读的感觉是，唉，还不如就保留在记忆里算了。

一句话作为一段，一段作为一个记忆。所谓人生，也不过是各种片段组成的零散回忆。

*** 苏自由
**** 重启世界：ChatGPT 之父山姆·奥特曼传
可以作为初步的了解，对于山姆以及 openAI 的历史。作者没有 Isaacson 的笔力，无法深入山姆的内心。

*** 唐德刚
**** 毛泽东专政始末
作为一个口述派的历史学家，唐德刚的历史叙述有独到之处。关于毛泽东的权力斗争，尤其建国后的历次斗争，此书提供了一些海外人士的见解，可作为旁证。

*** 胡适杂忆
关于胡适的形象，通过这本书更立体了。我们知道了胡适之所以了不起，也明白了为什么说胡适的观点很快会过时，但胡适的思想，永远闪耀。

只是唐德刚的文笔和口述方式，比较啰唆，也很个人化，实在是不能反复阅读。

*** 万维钢
**** 拐点
关于现代 AI，万维钢在这本书有科普性的介绍。但是此书的很多内容都是来自于《权力与预测》，我看那本书觉得有点枯燥，万维钢可以把道理深入浅出的讲出来，这是他的本事。但此书还是停留在科普阶段，读一遍就可以了。

*** 魏斐德
**** 中华帝国的衰落                                              
虽然作者被称为美国研究汉学的三杰之一，但此书对于中华帝国的衰落原因分析得并不深刻，也不全面。大概，此书成书较早，对于历史脉络是准确的。可以看一看，外国人是怎么看待晚清中国的各种事件。

*** 吴军
**** 脉络
对于历史和人生，吴军给出了自己的思考和建议。一些有深度，一些很平常。值得一读，但是呢，读完了记住了就行了。不需要多看。

*** 萧冬连
**** 筚路维艰
中国为什么会选择社会主义，以及为什么会变成“改良”版的社会主义，从 1940 年代到现在，经历了大约 5 次变革。--- 当然，从 2015 年起，应该是第六次改变了。本书基本比较客观，大致写法相当于 80 年代的历史学者的水平，在当前的环境下，已经属于上乘的水准了。

*** 熊培云
**** 重新发现社会
虽然这本书得了奖，但是内容很松散。也许我明白作者想表达，建立一个民主自由的社会，但是整个书的结构、资料，都无法引起我过多的兴趣。

*** 杨继绳
**** 中国改革年代的政治斗争                                      
中国从结束文革到南巡，实际上发生了很多次政治思想斗争：清除精神污染、反自由化、六四......，本书描写了两种不同思想的斗争：保守主义和改革派。看完之后，很是唏嘘，为什么中国的现代化进程如此艰难？为什么我们总是在反复？

成书较早，对于加入 WTO 之后的斗争，尤其这几年的政治变化，没有涉及，此为遗憾。

*** 叶文彬
**** Emacs Lisp 简明教程
很多讲解 Elisp 的书籍，上来就是语法或者大段的代码演示。实际上，最好的方法应该是先说基本的思想，然后用案例来说明如何 code。这本书作为 Elisp 的入门教程，是可以的。毕竟在水木清华的 Emacs 版块上作为精化存在过。

*** 易中天
**** 品读中国书系之一：大话方言                   
虽然我总觉得易中天的书，“借鉴”他人的很多，但如果不看别人的原文，直接看他的书也还可以。关于方言的特色，尤其广东、福建、江苏等地的南方语系，这本书还是能增长不少见识的。可以翻一翻。
**** 
**** 品读中国书系之二：品人录
对曹操、武则天，易中天都有客观的描述，也比较符合我的品人标准。所以，大概好人、坏人，英雄、奸雄，也不过是后人按照自己的标准来套而已。而自己哪里有什么真正的标准呢？

**** 品读中国书系之四：闲话中国人
易中天写书，有时候有趣，常常又啰唆。这本书就是典型的啰唆又有点意思的书。大概，这样的书，适合来做报告，而不是用来读。真读起来，实在是觉得废话太多。

*** 尹烨
**** 了不起的基因
尹烨的短视频还可以，写出来的书，简直就只是知识的罗列，没有什么可读性。对于了解一点基因知识，这本书或许有点用，但用处太有限了。

*** 俞敏洪
**** 我曾走在崩溃的边缘
关于新东方的发展以及个人在之中的思考，有一些反映。不能作为新东方的传记来看，更多的是个人体会。有一些借鉴意义，但随着时间的推移，我怀疑价值越来越小。

*** 张鸣
**** 张鸣重说中国近代史
**** 张鸣重说晚清民国
虽然中国近代史的大部分内容都清楚，但是有些细节经过张鸣的论述，更加了解在当时的背景下，中国社会各阶层的人，是如何想的。这本书作为一般野史补充，可以翻一翻。

*** 张维迎
**** 理念的力量
张维迎关于市场和改革的认识，我是非常认可的。他这本书重点强调基于少数人的理念更新，可以带来巨大的社会变革。有些精英意识，我也是认同的。

*** 周志明
**** 智慧的疆界：从图灵机到人工智能
全面地回顾了人工智能发展的历史，还有些半专业的描述。但确实对于人工智能这样“火”的方向，任何超过3年以上的书，都可以归结于“过时”。

** 一星 (32）
*** Denis Rothman
**** Transformers for Natural Language Processing and Computer Vision
重要的概念讲解不是很清晰，无关紧要的细节倒是啰里啰唆。看这本书，没有高屋建瓴，只有细节堆砌。

*** Eli Stevens & Luca Antiga & Thomas Viehmann
**** Deep Learning with PyTorch
这本书看了两次，都看不下去，实在是既没有把 PyTorch 讲清楚，也没有把 deep learning 讲清楚。

*** Jeffery Owens
**** Understanding Langchain: A Comprehensive Guide to Crafting Futuristic Language Model Applications
概念和代码都极其简略，如果没有其他的辅助知识，单靠这本书是无法理解任何一个概念的。即使是作为大纲复习，也几乎毫无价值。

*** Meredith Broussard
**** 人工不智能：计算机如何误解世界
虽然万维钢给这本书写了推荐序言，但这本书在我看来，完全是落后于时代的。作者还是哈佛大学当年计算机唯六的女生，但在人工智能发展的今天，她的观点即使不是杞人忧天，也只能算是庸人自扰了。

从今天的角度，这本书已经过时了，而且她的观点：计算机不是万能的。也毫无价值，等于没说。

*** Mohamed M. Hammad
**** Artificial Neural Network and Deep Learning: Fundamentals and Theory
讲的太繁琐和啰唆了，而关键的思想并没有很清晰，读了之后，反而会让人糊涂。作为参考资料呢，又有些不够。

*** Robert Scheinfeld
**** 你值得过更好的生活                                        
强行地把人生哲学和量子物理联系起来，实际上没有任何道理。虽然两边独立起来的描述也许是“对的”，但并没有因果关系，只是类比。很多“文科”强行做类比，乍一看似乎还有因果道理，其实只是幻觉。比如，辜鸿铭说，男人和女人就像茶壶和茶杯，只有一把茶壶配四个杯子，哪有一个杯子配四把茶壶的呢？所以男人可以有四个老婆，而女人不能有四个丈夫。可是，谁说男人女人的关系是茶壶和茶杯的关系了？为什么不说男女就像筷子和筷子篓的关系？这样我们就可以说，只有一个筷子篓就可以放十双筷子，哪有一支筷子能放入十个筷子篓的？这样，一个女的不就可以有十个丈夫，而一个男的，怎么可以娶多个妻子了？

所以，凡是类比，都要小心。他们并不是因果，所以并没有逻辑关系。文科的很多书，更像说明，而不是证明。
**** 
*** Sebastian Raschka
**** Machine Learning Q and AI: 30 Essential Questions and Answers on Machine Learning and AI
即使是我喜欢的 Sebastian，这本书也觉得参考意义不大。问题浅尝辄止，还不如看一本深入的书。大概这些书作为临时翻翻还可以，但完全不能细读。

**** Transformers for Natural Language Processing Build, train & fine-tune deep neural network architectures for NLP & Python, Hugging Face & OpenAI's GPT-3, ChatGPT & GPT-4, 2
同上本书一样，实在是没有讲清楚基本概念。

*** Vishnu Subramanian
**** Deep Learning with PyTorch
这本书有点老了，很多代码都运行不过去。

*** 戴建业
**** 我的个天
**** 戴老师高能唐诗课
戴建业初次在网络上看时，觉得幽默风趣。仔细看他的书，唉，惨不忍睹。不值得花时间看。

*** 高华
**** 历史的云雾
高华的研究方向是中国的党史和现代史。这本书是一些文章的合集，对于了解 AB 团等，有一定参考价值。但是呢，不看也无所谓的。

*** 何帆
**** 变量 1 2 3
罗胖把何帆吹到天上去了，《变量》系列，我完全不知所云。

*** 孔飞力
**** 中国现代国家的起源
虽然是著名汉学家写的，但确实没有什么新的东西，或许是书太早了吧。可读性也不强。

*** 李开复
**** 创业就是要细分垄断                                      
对于创业的一些认识，努力找到细分市场的特殊点，尽量做到第一。如果不能做到第一，那就再细分，定语如果足够多，一定能找到第一。创业不能做到第一，很快就会被大的企业干掉。
实际上，这本书读不读都没什么太大影响，深度不够。

**** AI·未来  
这本书确实老了，而且李开复的写作风格，我已经不能接受了。想起 20 年前，他写《世界因你不同》，我还追的不行。实在是时过境迁了。

**** AI 未来进行式
找了一个科幻作家来合著，其实是一个败笔。也许受众大概是普通公众，对于科技是“小白”的人。但对于我来说，几乎没有价值。

*** 李筠
**** 西方史纲 50 讲
**** 罗马史纲
李筠这两本书基本就是事实的罗列，故事趣味性和思想性都乏善可陈。大概适合中小学生阅读：知道有这么回事。但是，为什么会有这样的事情发生呢？并没有论述。

*** 刘润
**** 胜算：用概率思维提高胜算
书的开头，还有点意思，但10页以后，就一页不如一页。整本书，就像一部隐含的心灵鸡汤，再加一点说教。唉，《得到》上的商业书籍，大多这种水准，实在是不耐看。

*** 倪匡
**** 我看金庸系列 I
**** 我看金庸系列 II
**** 我看金庸系列 III
**** 我看金庸系列 IV
**** 我看金庸系列 V
本来金庸的小说有很多值得讨论之处，但倪匡的解说，并不有新意，比六神磊磊都不如。

*** 沈栋
**** 红色轮盘
这本书在 YouTube 上被吹的很高，据说讲了很多机密。实际上，文笔也不好，事情也不好。唯一的亮点，就是揭露了一点点温家宝家族的内幕。不用看，也知道的。

*** 王珞
**** 升维
王珞的视频讲解还可以，写书就有些肤浅了。表面上，这本书是想告诉大家，看待问题要扩展维度、提升维度，这样视角就会更广，就不会限于某个死结中。书中大量运用了博弈论的知识，但是实际效果很不好，几乎就是事情和知识点的罗列。可以不看。

*** 温伯陵
**** 一读就上瘾的中国史                                        
写法有点创新，把某一个主题的很多历史时间串到一起讲。但是，几乎没有新意，没有真知灼见，更像是年轻人的粗浅感想而已。不值得一读。

*** 杨健楷
**** 中国芯片往事
这本书打着说中国芯片发展历史的旗帜，内容一塌糊涂。对自己熟悉的步步高，就写了一半的篇幅。步步高算什么中国的芯片制造企业？比起 Miller 写的《Chip War》，简直一个天上一个地下。

*** 易中天
**** 品读中国书系之三：中国的男人和女人
开头还不错，语言犀利。后面太过啰唆，关于两性的心理和历史，读不读都无所谓，没有新意。

*** 余秋雨
**** 君子之道
本来书的题目很好，内容也可以很有趣。但余秋雨的矫揉造作，实在是让人大倒胃口。

* Movies
